version: '3'
services:
  sonos-display:
    image: rule88/sonos-display
    restart: unless-stopped
    network_mode: "host"
    environment:
      - PORT="${PORT}"
      - SPEAKER_NAME="${SPEAKER_NAME}"